# fly.toml app configuration file generated for markdb-frontend on 2025-11-19T15:14:19-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'markdb-frontend'
primary_region = 'ord'

[build]
  dockerfile = '../Dockerfile'

[build.args]
  BUILD_CONTEXT = '..'

[processes]
  app = "bun run start"

[env]
  NODE_ENV = 'production'
  VITE_API_URL = 'https://markdb-backend.fly.dev'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
