# fly.toml app configuration file generated for markdb-backend on 2025-11-19T15:13:33-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'markdb-backend'
primary_region = 'ord'

[build]
  dockerfile = '../Dockerfile'

[processes]
  app = "bun backend/app.ts"

[env]
  NODE_ENV = 'production'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
